name: weatherapp
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.3.10
  shared_preferences: ^0.5.6+3
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  flare_flutter: ^2.0.1
  custom_radio_grouped_button: ^1.0.0
  intl: ^0.16.1


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
